### ISSUE TITLE
Create valid import libs from mingw .def files

### ISSUE THREAD

**Issue by iainnicol** [martell/mingw-w64-clang#1]
Thanks for this project. I saw you mention it on HN.

Is it possible to create usable import libs from the mingw-w64 .def files? A few months ago, before I discovered this repo, I tried using llvm-dlltool. This almost worked, but had a problem.

The symbols in the created libs were of type IMPORT_NAME_NOPREFIX. However, the official MSVC libs have symbols with type IMPORT_NAME_UNDECORATE.

The mingw-w64 .def files only have one symbol name per symbol. They do not seem to use the equals sign to specify that the external and internal symbol names are different. That could be done, but it would be a huge rewrite of the .def files. Do you have a better solution?

**Comment by martell** [comment]
> Thanks for this project. I saw you mention it on HN.

Awesome, I'm glad you like it :)

> Is it possible to create usable import libs from the mingw-w64 .def files? A few months ago, before I discovered this repo, I tried using llvm-dlltool. This almost worked, but had a problem.
> The symbols in the created libs were of type IMPORT_NAME_NOPREFIX. However, the official MSVC libs have symbols with type IMPORT_NAME_UNDECORATE.

Mingw def files are subtly different from MSVC because of decisions made in binutils long ago.
Could you give me more context around the issue you are having and is there a specific use case for having them the exact same?

I can tell you where various functions to make these change are if you want to try tackling this.
Here is where the code lives for doing this in llvm-dlltool.
https://github.com/llvm-mirror/llvm/blob/master/lib/Object/COFFModuleDefinition.cpp#L59

We would have to change binutils, mingw-w64, llvm-dlltool and lld to flip this to the same as MSVC which is a big undertaking across the various projects.
I looked at this awhile back but in the end opted not to do this and focused more on getting clang and lld more usablebecause it would be an abi break between binutils mingw-w64 which I didn't have the time to manage and/or be responsible for.

We do generally have support for decorated symbols. See the following tests.
https://github.com/llvm-mirror/llvm/blob/master/test/tools/llvm-dlltool/coff-decorated.def
We just opt to do some adjusting

> The mingw-w64 .def files only have one symbol name per symbol. They do not seem to use the equals sign to specify that the external and internal symbol names are different. That could be done, but it would be a huge rewrite of the .def files. Do you have a better solution?

The weak external spec from my understanding is just like aliasing function names.
It does not differentiate from internal and external aliases and just swaps the function name at link time.

It may be possible to link up a function to a different function in the same dll by adjusting the symbol name to point to a different offset in the import library llvm-dlltool creates.
I have not tested this though and lib.exe might just outright not like this at all.
It has been awhile since I looked at the spec/library format so my thinking might even be wrong here.

Anyway, we use a double equals sign to signify a weak external. See, the following test case.
https://github.com/llvm-mirror/llvm/blob/master/test/tools/llvm-dlltool/coff-weak-exports.def

I hope this gives some insight to your problem.

**Comment by iainnicol** [comment]
Thanks for your detailed response, and the code pointers.

I was trying to do something very obscure: compile code with the Rust compiler thinking it was targetting MSVC, whilst really using clang with MinGW libs. To be honest, it required surprisingly few hacks.

Noted and agreed that making breaking ABI changes to four projects is waaayy too much effort. Instead I'll just maintain a one line fork of lld to treat IMPORT_NAME_NOPREFIX like IMPORT_NAME_UNDECORATE.

Thanks again for the information.
